Feature/network fixes
Wappsto/wappsto-python pull request #125
Opened 2020-05-14 09:43 UTC by tacozMacleo

Have Changed the Network flow, to be more thread safe. (The Rest require a redesign)
And added a poke, for the send Thread, so it known something have changed, and it might be able to send again.

2020-05-14 11:25 UTC, tacozMacleo commented
And It seams that development branch did not have the feature/cleanup merged ind. So the seluxit_rpc have been downgraded from a class to a utils lib. Change some structure to make it easier readable, and some redundant code that was not used, and many more.

2020-05-15 08:29 UTC, AndreasBomholtz requested changes

2020-05-15 08:29 UTC, AndreasBomholtz commented on wappsto/connection/receive_data.py
> +# RECEIVE_SIZE = 1024
Remove old code.

2020-05-15 08:29 UTC, AndreasBomholtz commented on wappsto/modules/value.py
> +        # self.parent.parent.conn.send_data.send_report(msg)
Delete old code.

2020-05-15 08:29 UTC, AndreasBomholtz commented on wappsto/__init__.py
> +                     (default: "wappsto.com")
Default address is collector.wappsto.com

2020-05-15 08:29 UTC, AndreasBomholtz commented on wappsto/__init__.py
> +                  (default: 11006)
The default port is now 443

2020-11-10 13:58 UTC, closed without merging